export const coursesData = [
  {
    id: 1,
    title: "IT Business Analysis",
    description:
      "Learn to bridge the gap between business needs and technology solutions",
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Gagan Verma",
    instructorRole: "Senior Business Analyst",
    students: "50+ Students",
    rating: 4.8,
    price: "₹299",
    duration: "10+ Lessons",
    category: "Business & Tech",
  },
  {
    id: 2,
    title: "Business Development",
    description: "Master the art of growing businesses and generating leads",
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Sarah",
    instructorRole: "Business Development Manager",
    students: "45+ Students",
    rating: 4.7,
    price: "₹249",
    duration: "8+ Lessons",
    category: "Business",
  },
  {
    id: 3,
    title: "Digital Consulting",
    description: "Learn to help businesses navigate digital transformation",
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Aman",
    instructorRole: "Digital Strategy Consultant",
    students: "40+ Students",
    rating: 4.9,
    price: "₹349",
    duration: "12+ Lessons",
    category: "Consulting",
  },
  {
    id: 4,
    title: "Robotic Process Automation",
    description: "Automate business processes with modern RPA tools",
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Tushar",
    instructorRole: "RPA Developer",
    students: "35+ Students",
    rating: 4.6,
    price: "₹399",
    duration: "15+ Lessons",
    category: "Technology",
  },
  {
    id: 5,
    title: "Artificial Intelligence",
    description:
      "Explore AI concepts, machine learning, and practical applications",
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Tushar",
    instructorRole: "AI Research Scientist",
    students: "60+ Students",
    rating: 4.9,
    price: "₹499",
    duration: "20+ Lessons",
    category: "Technology",
  },
  {
    id: 6,
    title: "Project Management",
    description: "Master project planning, execution, and delivery",
    image: "/placeholder.svg?height=200&width=300",
    instructor: "Tarun Singh",
    instructorRole: "Senior Project Manager",
    students: "55+ Students",
    rating: 4.8,
    price: "₹299",
    duration: "12+ Lessons",
    category: "Management",
  },
];
